package com.example.demo.models;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * MODEL CLASS: IncidentTicket
 * This class represents a support ticket in the SmartUni system.
 * It is stored in the "incident_tickets" collection in MongoDB.
 */
@Document(collection = "incident_tickets")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class IncidentTicket {

    @Id
    private String id; // Unique ID generated by MongoDB

    private String ticketCode; // Professional human-readable code (e.g., TKT-1001)
    private String title;      // Short summary of the issue
    private String description; // Detailed explanation of the problem
    private String category;    // Category (e.g., PLUMBING, ELECTRICAL, IT)
    private String resourceId;  // Link to a specific campus asset/resource
    private String location;    // Physical location on campus (Room number, Hall, etc.)
    
    // Contact information for the person reporting the issue
    private String preferredContactName;
    private String preferredContactEmail;
    private String preferredContactPhone;
    
    private TicketPriority priority; // Level of urgency: LOW, MEDIUM, HIGH, EMERGENCY
    private TicketStatus status;     // Lifecycle stage: OPEN, ASSIGNED, IN_PROGRESS, RESOLVED, CLOSED, REJECTED

    private String createdBy;          // ID of the student or staff member who created the ticket
    private String assignedTechnician; // ID of the technician responsible for fixing it
    
    private String resolutionNotes; // Notes added when the issue is fixed
    private String rejectionReason; // Reason if the ticket was declined by an admin

    // History and communication logs
    private List<Attachment> attachments = new ArrayList<>(); // Files uploaded (images/logs)
    private List<TechnicianUpdate> updates = new ArrayList<>(); // Log of work progress by the technician
    private List<Comment> comments = new ArrayList<>();        // Communication between user and technician

    // Audit timestamps
    @CreatedDate
    private LocalDateTime createdAt; // Set automatically when ticket is created

    @LastModifiedDate
    private LocalDateTime updatedAt; // Set automatically when ticket is updated
    
    private LocalDateTime resolvedAt; // When the technician marks it as fixed
    private LocalDateTime closedAt;   // When the admin/user confirms and closes the ticket
}
