spring.application.name=smart-campus

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus

# JWT
jwt.secret=SmartCampus2026SuperSecretKeyForJWTSigning!MustBe256BitsLong
jwt.expiration-ms=86400000

# Server
server.port=8080

# Google Auth
google.client-id=1039009642724-27g0qkbtfndt41hgh0eltecfabn12k03.apps.googleusercontent.com

# Logging
logging.file.name=logs/spring.log
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG

# Email (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gamagedissanayake1021@gmail.com
spring.mail.password=ebjh ekdv bfan kzms
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
