spring.application.name=smart-campus

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus

# JWT
jwt.secret=SmartCampus2026SuperSecretKeyForJWTSigning!MustBe256BitsLong
jwt.expiration-ms=86400000
